In [55]:
import pandas as pd

In [56]:
df_24 = pd.read_csv("data/df_asociacion_24.csv")
df_150 = pd.read_csv("data/df_asociacion_150.csv")

df_mutacion1 = pd.read_csv("data/releases_2023_v4release_1027_amp_pd_participant_apoe_mutations.csv")
df_mutacion2 = pd.read_csv("data/releases_2023_v4release_1027_amp_pd_participant_mutations.csv")


df_mutacion1

      participant_id APOE_genotype  APOE_E4_status
0            BF-1001         E3/E3               0
1            BF-1002         E3/E3               0
2            BF-1003         E3/E3               0
3            BF-1004         E3/E3               0
4            BF-1005         E3/E3               0
...              ...           ...             ...
10470       PP-73134         E2/E3               0
10471       PP-73614         E3/E3               0
10472       PP-73787         E3/E3               0
10473       PP-74199         E3/E3               0
10474       PP-74763         E2/E3               0

[10475 rows x 3 columns]

Vamos a elegir en ambos dataframes unicamente los datos procedentes de PPMI

In [57]:
df_mutacion1 = df_mutacion1[df_mutacion1["participant_id"].str.contains("PP-")]
df_mutacion2 = df_mutacion2[df_mutacion2["participant_id"].str.contains("PP-")]

df_mutacion = df_mutacion2

df_mutacion = df_mutacion.rename(columns={"participant_id": "PATNO"})
df_24["PATNO"] = df_24["PATNO"].astype(str)
df_mutacion["PATNO"] = df_mutacion["PATNO"].astype(str)
df_mutacion["PATNO"] = df_mutacion["PATNO"].str.replace("PP-", "", regex=False)

df_mutacion

,PATNO,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS
8023,3000,No,No,No,No,No
8024,3001,No,No,No,No,No
8025,3002,No,No,No,No,No
8026,3003,No,No,No,Yes,Yes
8027,3004,No,No,No,No,No
...,...,...,...,...,...,...
10470,73134,No,Yes,No,No,Yes
10471,73614,Yes,No,No,No,Yes
10472,73787,Yes,No,No,No,Yes
10473,74199,Yes,No,No,No,Yes
10474,74763,Yes,No,No,No,Yes

In [58]:
df_150["PATNO"] = df_150["PATNO"].astype(str)

Vamos a unir el .CSV que contiene la información con las mutaciones al .CSV que ya tenemos con el resto de los datos clínicos y de SAA

In [59]:
df_24_completo = df_24.merge(
    df_mutacion,
    on=["PATNO"],
    how="left"
)

df_150_completo = df_150.merge(
    df_mutacion,
    on=["PATNO"],
    how="left"
)

df_24_completo = df_24_completo.sort_values(by="PATNO")
df_150_completo = df_150_completo.sort_values(by="PATNO")

bins = [0, 50, 60, 70, 120]
labels = ["<50", "50-59", "60-69", "≥70"]

df_24_completo["age_group"] = pd.cut(df_24_completo["age_at_baseline"], bins=bins, labels=labels)
df_150_completo["age_group"] = pd.cut(df_150_completo["age_at_baseline"], bins=bins, labels=labels)

col = df_24_completo.pop("age_group")
df_24_completo.insert(7, "age_group", col)
col = df_150_completo.pop("age_group")
df_150_completo.insert(7, "age_group", col)

df_24_completo.to_csv("df_24_mutaciones.csv")
df_150_completo.to_csv("df_150_mutaciones.csv")

df_150_completo

,Unnamed: 0.1,Unnamed: 0,PATNO,GUID,CLINICAL_EVENT,visit_month,age_at_baseline,age_group,sex,ethnicity,...,prodromal_category,study_arm,diagnosis,COHORT,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS
515,808,6172,10874,NaN,BL,-1.0,73.0,≥70,Female,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,Yes,Yes
394,617,4831,12224,NIHUN440CUNRR,BL,-1.0,66.0,60-69,Female,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,Yes,Yes
516,810,6198,12593,NaN,BL,-1.0,66.0,60-69,Female,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,Yes,Yes
263,399,3108,13039,NIHLU969RYBRK,BL,-1.0,67.0,60-69,Male,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,No,No
517,811,6212,13424,NaN,BL,-1.0,76.0,≥70,Female,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,1976,14455,90456,NaN,BL,-1.0,82.0,≥70,Male,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Negative,No,No,No,No,No
320,494,3864,91097,NIHPM376XMEFF,BL,-1.0,67.0,60-69,Male,Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,Yes,Yes
1116,1977,14471,91837,NaN,BL,-1.0,74.0,≥70,Male,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Negative,No,No,No,No,No
64,97,652,92490,NIHCW801ZWXWW,BL,-1.0,72.0,≥70,Male,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,No,No
1117,1978,14473,92834,NaN,BL,-1.0,66.0,60-69,Male,Not Hispanic or Latino,...,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive,No,No,No,Yes,Yes